# Generated by Django 3.1 on 2020-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_apply_cearted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='cv',
            field=models.FileField(default=1, upload_to='apply/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='website',
            field=models.URLField(),
        ),
    ]
